---
global:
  gc: {{.GC}}
  gcMetrics: {{.GC_METRICS}}
  indexerConfig:
    esServers: ["{{.ES_SERVER}}"]
    insecureSkipVerify: true
    defaultIndex: {{.ES_INDEX}}
    type: {{.INDEXING_TYPE}}
  measurements:
    - name: podLatency
      thresholds:
        - conditionType: Ready
          metric: P99
          threshold: {{.POD_READY_THRESHOLD}}
{{ if eq .SVC_LATENCY "true" }}
    - name: serviceLatency
      svcTimeout: 10s
{{ end }}
jobs:
  - name: cluster-density-v2
    namespace: cluster-density-v2
    jobIterations: {{.JOB_ITERATIONS}}
    qps: {{.QPS}}
    burst: {{.BURST}}
    namespacedIterations: true
    podWait: false
    waitWhenFinished: true
    preLoadImages: true
    preLoadPeriod: 15s
    churn: {{.CHURN}}
    churnCycles: {{.CHURN_CYCLES}}
    churnDuration: {{.CHURN_DURATION}}
    churnPercent: {{.CHURN_PERCENT}}
    churnDelay: {{.CHURN_DELAY}}
    churnDeletionStrategy: {{.CHURN_DELETION_STRATEGY}}
    namespaceLabels:
      security.openshift.io/scc.podSecurityLabelSync: false
      pod-security.kubernetes.io/enforce: privileged
      pod-security.kubernetes.io/audit: privileged
      pod-security.kubernetes.io/warn: privileged

    objects:

      - objectTemplate: deployment-server.yml
        replicas: 20
        inputVars:
          podReplicas: 2

      - objectTemplate: deployment-client.yml
        replicas: 20
        inputVars:
          podReplicas: 2
          ingressDomain: {{.INGRESS_DOMAIN}}

      - objectTemplate: service.yml
        replicas: 75
        
      - objectTemplate: secret.yml
        replicas: 20

      - objectTemplate: service-np.yml
        replicas: 4

      - objectTemplate: configmap.yml
        replicas: 15

      - objectTemplate: np-deny-all.yml
        replicas: 1

      - objectTemplate: np-allow-from-clients.yml
        replicas: 1

      - objectTemplate: np-allow-from-ingress.yml
        replicas: 1

      - objectTemplate: np-allow-from-same-namepsace.yml
        replicas: 1

